### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by runephilosof** [android-async-http/android-async-http#1212]
1.4.9 contains major changes, it would have been nice if you had published it as 2.0.0 instead.
It would be nice if you could remove 1.4.9 and publish it as 2.0.0 instead.
But I guess that isn't feasible, since I guess that would break the builds of those that have already migrated to 1.4.9?

**Comment by smarek** [comment]
Yes, I'm sorry, 1.4.9 was release when I still got time to invest, then it took 3 years for me to get back to library, loopj abandoned. Now it's again open and even open to adding new maintainers/developers.

I'm not going to de-publish 1.4.9, since that would break things for everybody in my opinion.

Major changes are currently done in 1.5 but I will consider releasing at as 2.0.0, thank you for suggestion
