### ISSUE TITLE
https://github.com/loopj/android-async-http/issues/746 question not resolve

### ISSUE THREAD

**Issue by mzhs-git** [android-async-http/android-async-http#1310]
The above code still does not solve my problem.
Exception info:
SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
sslsocketfactory set:
asynclient.setSSLSocketFactory(MySSLSocketFactory.getFixedSocketFactory());

server only support tls1.2
andorid 4.4.4

when I add
HttpsURLConnection.setDefaultSSLSocketFactory(new NoSSLv3Factory());
before
AsyncHttpClient client = new AsyncHttpClient();
and remove
asynclient.setSSLSocketFactory(MySSLSocketFactory.getFixedSocketFactory());
Exception info:
no peer cer..

Both codes are added，Exception info:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

Can anyone help me with this?

Thanks

**Comment by smarek** [comment]
Please, provide debug info. What version of library, and provide [KISS](https://en.wikipedia.org/wiki/KISS_principle) sample of code (init of library, public server which supports), otherwise no help will be provided here, and you should turn to stackoverflow.com for help

Re-open this issue if you provide requested debug info
