### ISSUE TITLE
null ResponseHandlerInterface parameter in post method causes app to crash

### ISSUE THREAD

**Issue by vincentnock** [android-async-http/android-async-http#416]
It worked well on 1.4.3

**Comment by anubiann00b** [comment]
I think this is the expected behaviour:

https://github.com/loopj/android-async-http/blob/master/library/src/main/java/com/loopj/android/http/AsyncHttpClient.java#L1301

In my opinion responseHandler should be nullable, or there should be some way to construct a response handler that discards the response. That should be discouraged, but not prevented.

**Comment by smarek** [comment]
@anubiann00b well if he passes null responsehandler to method, it should crash with linked exception. I'm not going to remove the check, because it should be done intentionally to ignore the output of command, so I'll provide BlackholeAsyncHttpResponseHandler, which discards everything, that sounds good, doesn't it?

**Comment by anubiann00b** [comment]
Yup, sounds awesome. Love the name too :)

**Comment by smarek** [comment]
Provided, and will be available in 1.4.8 release, see the linked commit

**Comment by anubiann00b** [comment]
:+1:
