### ISSUE TITLE
Set proxy in system settings won't change the proxy of android async http as well in 1.4.9

### ISSUE THREAD

**Issue by YlorD** [android-async-http/android-async-http#971]
Today I updated AAH from 1.4.7 to 1.4.9 in order to solve the apache http client problem in SDK 23. However, I found that the system proxy set in Android wifi settings won't take effect in my app when I update successfully to 1.4.9. I just can't analyse the http request of my app. Now I have to set the proxy manually by AsyncHttpClient#setProxy. That's not an ideal way cause hard coding is really a frustrating thing. Could anyone please help me? Thanks a lot in advance.

**Comment by YlorD** [comment]
Update.

I can get system proxy host and port by System.getProperty but what I wonder is that why I don't need to do so before I update the version of AAH to 1.4.9. Besides, I'm not sure whether this is the best way to sync the system proxy setting to AsyncHttpClient.

**Comment by smarek** [comment]
Hi, if you're just using default system proxy, you don't need to do anything, as system will put your requests through configured proxy automatically.

Why do you do this manually? Is there any specific Android version / device configuration, where this doesn't work by default?

**Comment by YlorD** [comment]
I just don't know why.

The SDK version is 23. I set the system proxy in wifi settings. I'm not sure whether this is a special case. I've tried a lot of times since this afternoon but it's all the same if I don't set the proxy manually.

**Comment by smarek** [comment]
Well in that case I can think of possible solution:
Subclass AsyncHttpClient and override method `newAsyncHttpRequest`, there set current system proxy to HttpClient connection params, which will cause each request to have up-to-date system proxy.
Of course it doesn't solve situation where network and/or proxy changes when the request is already in the queue, but should provide the best flexibility against system settings.

Second option is to return your custom subclass of `AsyncHttpRequest` from the `newAsyncHttpRequest` method, which would set the proxy params before executing request, which would be always most up-to-date probably only milliseconds before request will execute.

**Comment by LanceKersey** [comment]
I just wanted to comment that I have the same issue after upgrading to 1.4.9. I use the Android proxy settings to sniff traffic in Charles, but the traffic no longer routes through there.

I can sniff traffic fine in Wireshark, since it does not require using a proxy, but Wireshark doesn't display HTTP requests in an organized manner, so it takes a lot more time to analyze than in Charles.

I will try manually setting the proxy as suggested, but there still is the issue of why we need to do this and why it stopped working in the first place.

**Comment by YoungjaeKim** [comment]
OMG. I'm also writing same content abount this.

**Comment by ihanbo** [comment]
I ‘ve use a independent  httpclient library (" cz.msebera.android.httpclient" this one), so I set proxy manually , but fiddler is also not capture the request ,I've read the proxy from httpparams  and find it right ,I'm confused

**Comment by YoungjaeKim** [comment]
For anyone who has the problem, apply below code.

HttpClient = new AsyncHttpClient(true, 80, 443);
HttpClient.setProxy(System.getProperty("http.proxyHost"), Integer.parseInt(System.getProperty("http.proxyPort")));

**Comment by ihanbo** [comment]
@YoungjaeKim I've put the same code before every request, also didn't work well!

**Comment by YoungjaeKim** [comment]
@ihanbo Well, some related articles about `System.getProperty("http....")` reports that it gives unexpected result among Android version. Mine 5.0.1 is working fine, but my colleague's 4.3.3 is not working.

**Comment by LanceKersey** [comment]
I have looked into setting the proxy settings manually. The method to get the system proxy settings has changed more than once in Android, so already you have to implement them all, and hope one if them works on every device. But since it has changed more than once already, I would not be confident it will not change again after users have already downloaded your app, making such an implementation unsafe except for debugging (packet sniffing) purposes. I would not put such functionality in an app meant for users

You can see if your system has the http.proxyHost param pretty easily in an ADB console:
adb shell getprop http.proxyHost
adb shell getprop http.proxyPort

If there is no output, this method will not work on your device. It does not work on my Android 6.0 Nexus 6 or Nexus 6p.

There is even a library someone wrote to sort out all this nonsense for you. It says it only supports up to Android 4, but the last code commit was only 6 months ago, so who knows if it is maintained or works in recent Android versions:
https://github.com/shouldit/android-proxy/tree/master/android-proxy-library

**Comment by kuafoo** [comment]
I also got this problem  I use this to resolve it.

`if(BuildConfig.DEBUG)
        {
            String proHost = System.getProperty("http.proxyHost");
            int proPort = Integer.parseInt(System.getProperty("http.proxyPort"));
            if(!TextUtils.isEmpty(proHost) && proPort>0)
            {
                client.setProxy(proHost,proPort);
            }
            client.setLoggingEnabled(true);
        }`

**Comment by YoungjaeKim** [comment]
I ended up to fight proxy issue in loopj module, and create similar library using okhttp.
Take a look if you are interested. We are using this in production for months.
https://github.com/OpenBapul/HttpLibrary

**Comment by smarek** [comment]
This is tested and solved in latest 1.4.10 release
